module.exports = [
    { "code": 1 ,    "desc": "成功"  ,          "desc_eng": "success"} ,
    { "code": 500 ,  "desc": "系统错误" ,         "desc_eng": "system error" } ,
    { "code": 700 ,  "desc": "未登录或token已失效" , "desc_eng": "token does not exist or token invalid"} ,
    { "code": 900 ,  "desc": "参数不合法" , "desc_eng": "params is invalid"} ,
    { "code": 1000 , "desc": "俱乐部id错误" ,     "desc_eng": "club id error. "} ,
    { "code": 2000 , "desc": "俱乐部已存在" ,     "desc_eng": "this club already exist"} ,
    { "code": 2001 , "desc": "找不到俱乐部" ,     "desc_eng": "can not find club"} ,
    { "code": 2002 , "desc": "加入俱乐部成功" ,     "desc_eng": "join club successfully"},
    { "code": 2003 , "desc": "加入俱乐部错误" ,     "desc_eng": "club_id error, can not find this club"},
    { "code": 2004 , "desc": "请求账户名为空" ,     "desc_eng": "request account name empty"},
    { "code": 2005 , "desc": "请求账户名或者俱乐部 id 为空" ,     "desc_eng": "club or account_name does not exist"},
    { "code": 2006 , "desc": "俱乐部 id 为空" ,     "desc_eng": "club id does not exist"},
    { "code": 2007 , "desc": "房间 id 为空" ,     "desc_eng": "room id does not exist"},
    { "code": 2008 , "desc": "找不到房间信息" ,     "desc_eng": "con't find room infomation"},
    { "code": 2009 , "desc": "找不到房间结果" ,     "desc_eng": "con't find red envelope result infomation"},
    { "code": 2010 , "desc": "你已经创建过俱乐部" ,     "desc_eng": "You have created a club"},
    { "code": 2011 , "desc": "俱乐部名称已经存在" ,     "desc_eng": "club name already exist"},
    { "code": 2012 , "desc": "充值余额不足" ,     "desc_eng": "insufficient balance"},
    { "code": 2013 , "desc": "找不到红包" ,     "desc_eng": "not find this red envelope"},
    { "code": 2014 , "desc": "找不到 eos 账户" ,     "desc_eng": "can not find this eos account"},
    { "code": 2015 , "desc": "红包已抢完" ,     "desc_eng": "game over"},
    { "code": 2016 , "desc": "房间不符" ,     "desc_eng": "room incompatible"},
    { "code": 2017 , "desc": "已经抢过" ,     "desc_eng": "already snatched"},
    { "code": 2018 , "desc": "推荐人账号不存在" ,     "desc_eng": "account of referrer is not exist"},
    { "code": 2019 , "desc": "红包不存在" ,     "desc_eng": "red envelope is not exist"},
    { "code": 2020 , "desc": "提现余额不足" ,     "desc_eng": "Insufficient balance withdrawal"},
    { "code": 2021 , "desc": "验证码不正确" ,     "desc_eng": "verification code is incorrect"},
    { "code": 2022 , "desc": "推荐俱乐部不存在", "desc_eng": "Recommended club does not exist" },
    { "code": 2023 , "desc": "已建立推荐关系", "desc_eng": "Recommended relationship established" },
    { "code": 2024 , "desc": "不能与自己建立推荐关系", "desc_eng": "Can't establish a recommendation relationship with yourself" },
    { "code": 2025 , "desc": "不能使用该账号下的被推荐人作为推荐人建立关系", "desc_eng": "Cannot use the referee under this account as a referrer to establish a relationship" },
]