### 获取全球合伙人私募信息
GET http://localhost:9527/trade/raise_buy

### 获取普通买入交易信息
GET http://localhost:9527/trade/buy_assets

### 资产包买入记录
GET http://localhost:9527/trade/buy_assets_history?account_name=yujinsheng11

### 
POST http://localhost:9527/user_check_in
Content-Type: application/json

{
    "account_name": "gametestuser"
}

### 
GET http://localhost:9527/check_in?account_name=gametestuser

###
GET http://localhost:9527/check_in/detail?account_name=gametestuser

### raise
POST http://localhost:9527/trade/global_raise_buy
Content-Type: application/json

{
    "account_name": "yujinsheng11",
    "price": "0.500",
    "assets_package_id": 4
}

### raise
POST http://localhost:9527/trade/user_buy_assets
Content-Type: application/json

{
    "account_name": "t5234vtx51gs",
    "price": "1.800",
    "assets_package_id": 2
}

### 获取普通买入交易信息
GET http://localhost:9527/trade/sell_assets

### 资产包买入记录
GET http://localhost:9527/trade/buy_assets_history?account_name=yujinsheng11