###
GET http://localhost:9527/tbg/info

###
GET http://localhost:9527/tbg/destroy

###
GET http://localhost:9527/tbg/system_notification

###
POST http://localhost:9527/tbg/add_notification
Content-Type: application/json

{
    "creator": "yujinsheng11",
    "title": "TBG全球同步上线公告",
    "description": "TBG全球同步上线公告"
}



###
POST http://pog.tbg.isecsp.com/tbg/add_notification
Content-Type: application/json

{
    "creator": "yujinsheng11",
    "title": "TBG全球同步上线公告",
    "description": "TBG全球同步上线公告"
}