#!/bin/bash
#Description: run HASH_DICE service
unset HASH_DICE_DB_HOST
unset HASH_DICE_DB_PORT
unset HASH_DICE_DB_USER
unset HASH_DICE_DB_PASS
unset HASH_DICE_DB_NAME
unset HASH_DICE_REDIS_HOST
unset HASH_DICE_REDIS_PORT
unset HASH_DICE_REDIS_PASS
unset HASH_DICE_RABBIT_HOST
unset HASH_DICE_RABBIT_PORT
unset HASH_DICE_RABBIT_USER
unset HASH_DICE_RABBIT_PASS

set TBG_SERVER=http://192.168.1.141:9527/
set HASH_DICE_SERVER_HOST=0.0.0.0
set HASH_DICE_SERVER_PORT=13022


dbname=hash_dice
dbuser=hash_dice_user

set HASH_DICE_DB_HOST=192.168.92.128
set HASH_DICE_DB_PORT=5432
set HASH_DICE_DB_USER=%dbuser%
set HASH_DICE_DB_PASS=pass_2019
set HASH_DICE_DB_NAME=%dbname%

set HASH_DICE_REDIS_HOST=192.168.1.115
set HASH_DICE_REDIS_PORT=6379
set HASH_DICE_REDIS_PASS=redis_pass_2018

set HASH_DICE_RABBIT_HOST=192.168.1.115
set HASH_DICE_RABBIT_PORT=5672
set HASH_DICE_RABBIT_USER=mq_user
set HASH_DICE_RABBIT_PASS=pass_2018

node hash_dice.js
