### get account information
GET http://localhost:13021/global_lotto/info

### get config
GET http://localhost:13021/config/get_config

### get account information
GET http://localhost:13021/global_lotto/latest_game_session

### 获取所有期数及开奖信息 global_lotto.tbg.isecsp.com
GET http://localhost:13021/global_lotto/game_session

### 获取某一期开奖详情 
GET http://localhost:13021/global_lotto/game_session_detail?gs_id=d579f0928980405b

### get account information
GET http://localhost:13021/global_lotto/game_session_mine?account_name=gametestuser

### get account information
GET http://localhost:13021/global_lotto/game_session_mine_detail?account_name=gametestuser&bo_id=d597fe1a4f8edf21

### get account information
POST http://localhost:13021/global_lotto/bet
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXkiOiJnYW1ldGVzdHVzZXIiLCJpYXQiOjE1NzA2MjAyODksImV4cCI6MTU3MDY0MTg4OX0.Qij6R9kDkCrhOMe5H3zaFOHramB30VuV-C5vBYUyHKM

{
    "periods": 74,
    "account_name": "tbgtestuser1",
    "bet_num": "123456789",
    "bet_key": 1,
    "bet_amount": 0.1
}

### get account information
POST http://localhost:13021/global_lotto/random_bet
Content-Type: application/json

{
    "periods": 1,
    "account_name": "yujinsheng11",
    "bet_key": 15,
    "bet_amount": 1.5
}

####
curl -XPOST http://45.251.109.187:8888/v1/history/get_actions -H "Content-Type: application/json" -d '
{
    "pos": 1,
    "offset": 9,
    "account_name": "lottobanker"
}'