#!/bin/bash
#Description: run tbg service
unset SNATCH_TREASURE_DB_HOST
unset SNATCH_TREASURE_DB_PORT
unset SNATCH_TREASURE_DB_USER
unset SNATCH_TREASURE_DB_PASS
unset SNATCH_TREASURE_DB_NAME
unset SNATCH_TREASURE_REDIS_HOST
unset SNATCH_TREASURE_REDIS_PORT
unset SNATCH_TREASURE_REDIS_PASS
unset SNATCH_TREASURE_RABBIT_HOST
unset SNATCH_TREASURE_RABBIT_PORT
unset SNATCH_TREASURE_RABBIT_USER
unset SNATCH_TREASURE_RABBIT_PASS

export TBG_SERVER=http://pog.tbg.isecsp.com
export SNATCH_TREASURE_SERVER_HOST=0.0.0.0
export SNATCH_TREASURE_SERVER_PORT=13025

export SNATCH_TREASURE_DB_HOST=127.0.0.1
export SNATCH_TREASURE_DB_PORT=54321
export SNATCH_TREASURE_DB_USER=wallet_tbg_user
export SNATCH_TREASURE_DB_PASS=pass_2019
export SNATCH_TREASURE_DB_NAME=wallet_tbg_db

export SNATCH_TREASURE_REDIS_HOST=127.0.0.1
export SNATCH_TREASURE_REDIS_PORT=6380
export SNATCH_TREASURE_REDIS_PASS=iueksefPOSDds123DW

export SNATCH_TREASURE_RABBIT_HOST=172.18.0.2
export SNATCH_TREASURE_RABBIT_PORT=5672
export SNATCH_TREASURE_RABBIT_USER=mq_user
export SNATCH_TREASURE_RABBIT_PASS=pass_2019

ex=$(which pm2)
if [ ! -e $ex ];
then
    npm i -g pm2
fi

node snatch_treasure.js