#!/bin/bash
#Description: run GLOBAL_LOTTO service
unset GLOBAL_LOTTO_DB_HOST
unset GLOBAL_LOTTO_DB_PORT
unset GLOBAL_LOTTO_DB_USER
unset GLOBAL_LOTTO_DB_PASS
unset GLOBAL_LOTTO_DB_NAME
unset GLOBAL_LOTTO_REDIS_HOST
unset GLOBAL_LOTTO_REDIS_PORT
unset GLOBAL_LOTTO_REDIS_PASS
unset GLOBAL_LOTTO_RABBIT_HOST
unset GLOBAL_LOTTO_RABBIT_PORT
unset GLOBAL_LOTTO_RABBIT_USER
unset GLOBAL_LOTTO_RABBIT_PASS



export GLOBAL_LOTTO_DB_HOST=172.17.0.5
export GLOBAL_LOTTO_DB_PORT=5432
export GLOBAL_LOTTO_DB_USER=wallet_GLOBAL_LOTTO_user
export GLOBAL_LOTTO_DB_PASS=pass_2019
export GLOBAL_LOTTO_DB_NAME=wallet_GLOBAL_LOTTO_db

export GLOBAL_LOTTO_REDIS_HOST=172.17.0.6
export GLOBAL_LOTTO_REDIS_PORT=6379
export GLOBAL_LOTTO_REDIS_PASS=redis_pass_2018

export GLOBAL_LOTTO_RABBIT_HOST=172.17.0.4
export GLOBAL_LOTTO_RABBIT_PORT=5672
export GLOBAL_LOTTO_RABBIT_USER=mq_user
export GLOBAL_LOTTO_RABBIT_PASS=pass_2019

ex=$(which pm2)
if [ ! -e $ex ];
then
    npm i -g pm2
fi

pm2 start ./pm2.json